notifications:
  webhooks:
    urls:
      - http://52.4.116.120:8081/webhook
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
