# Copyright (c) 2017 Cable Television Laboratories, Inc. ("CableLabs")
#                    and others.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- hosts: all

  tasks:
    - name: Install Git
      become: yes
      become_method: sudo
      become_user: root
      apt: name=git

    - name: Delete snaps-oo source
      file:
        state: absent
        dest: ~/snaps-oo

    - name: Clone snaps-oo
      git:
        repo: https://gerrit.opnfv.org/gerrit/snaps
        dest: ~/snaps-oo

    - name: Delete snaps-oo virtualenv
      file:
        state: absent
        dest: ~/snaps-venv

    - name: Create virtualenv
      shell: /home/ubuntu/.local/bin/virtualenv ~/snaps-venv

    - name: Install snaps-oo
      shell: ~/snaps-venv/bin/pip install -e ~/snaps-oo

    - name: Copy RC file from control server @ {{ ctrl_admin_ip }}
      command: 'sudo scp -o StrictHostKeyChecking=no {{ ctrl_admin_ip }}:/etc/kolla/admin-openrc.sh ~/openrc'

    - name: Launch SNAPS-OO validation tests
      command: "~/snaps-venv/bin/python ~/snaps-oo/snaps/test_runner.py -e ~/openrc -n {{ ext_net_name }} -a -k -t 2"
      register: out
    - debug: var=out.stderr_lines
