---
- hosts: buildserver
  become: yes
  become_user: root
  vars_files:
    - ../common/variable.yaml
    - ../common/constants.yaml
  tasks:

    - name: Deploy ubuntu OS on host machines
      command: "python /tmp/{{ workspace }}/snaps-boot/iaas_launch.py -f {{ hosts_yaml_path }} -b"
      register: out
    - debug: 
        var: out

    - name: Validating iaas_launch returned 0
      fail: msg="iaas_launch.py -b command failed"
      when: out.rc != 0

    - name: Wait for 20 mins
      wait_for: timeout=1200

#change
    - name: Remove known hosts entries
      command: "ssh-keygen -f \"/root/.ssh/known_hosts\" -R \"{{ item }}\""
      with_items:
         - "{{ mgmt_prefix }}.{{ controller_ip }}"
         - "{{ mgmt_prefix }}.{{ compute_ip }}"
      ignore_errors: True
#change

    - name: Configure static IPs on host machines
      command: "python /tmp/{{ workspace }}/snaps-boot/iaas_launch.py -f {{ hosts_yaml_path }} -s"
      register: out1
    - debug: 
        var: out1

    - name: Validating iaas_launch returned 0
      fail: msg="iaas_launch.py -s command failed"
      when: out1.rc != 0

    - name: Wait for 10 mins
      wait_for: timeout=600

