---
- hosts: buildserver 
  become: yes
  become_user: root
  vars_files:
    - ../common/variable.yaml
    - ../common/constants.yaml
  environment:
     http_proxy: "{{ http_proxy }}"
     https_proxy: "{{ https_proxy }}"
     ftp_proxy: "{{ ftp_proxy }}"
     no_proxy: "{{ no_proxy }}"

  tasks:
#    - name: Clone snaps-openstack code
#      git:
#        repo: '{{ snaps_openstack_url }}'
#        dest: '/tmp/{{ workspace }}/snaps-openstack'
#        force: yes

    - name: Deploy OpenStack
      command: "python /tmp/{{ workspace }}/snaps-openstack/iaas_launch.py -f {{ deployment_yaml_path }} -drs"
      register: out
    - debug:
        var: out
 
    - name: Validating iaas_launch returned 0
      fail: msg="iaas_launch.py -drs command failed"
      when: out.rc != 0

