---
- hosts: buildserver 
  become: yes
  become_user: root
  vars_files:
    - ../common/variable.yaml
    - ../common/constants.yaml
  environment:
     http_proxy: "{{ http_proxy }}"
     https_proxy: "{{ https_proxy }}"
     ftp_proxy: "{{ ftp_proxy }}"
     no_proxy: "{{ no_proxy }}"

  tasks:

    - name: Deploy VLAN
      command: "python /tmp/{{ workspace }}/snaps-openstack/network_config.py -f {{ var_yaml_path }} -tvlan"
      register: out
    - debug:
        var: out
 
    - name: Validating VLAN
      fail: msg="network_config.py -tvlan command failed"
      when: out.rc != 0

    - name: Wait for 3 mins
      wait_for: timeout=180

