---
- hosts: controller 
  become: yes
  become_user: root
  vars_files:
    - ../common/variable.yaml
    - ../common/constants.yaml
    - /tmp/{{ workspace }}/admin-openrc.yaml
  environment:
     http_proxy: "{{ http_proxy }}"
     https_proxy: "{{ https_proxy }}"
     ftp_proxy: "{{ ftp_proxy }}"
     no_proxy: "{{ no_proxy }}"

  tasks:

    - name: Create SRIOV port
      os_port:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
          user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
        name: sriov-port
        network: public1


    - name: Update SRIOV port
      shell: source /etc/kolla/admin-openrc.sh;openstack port set sriov-port --vnic-type direct
      args:
       executable: /bin/bash


    - name: Find port ID
      shell: source /etc/kolla/admin-openrc.sh;openstack port list | grep sriov-port | awk {'print $2'}
      args:
       executable: /bin/bash
      register: result
    - debug: var=result.stdout

    - name: Create SRIOV instance
      shell: 'source /etc/kolla/admin-openrc.sh;openstack server create --flavor m1.medium --image ubuntu --nic port-id={{ result.stdout }} --key-name mykey test-sriov '
      args:
       executable: /bin/bash

    - name: Wait for 3 mins
      wait_for: timeout=180

    - name: Get IP of SRIOV instance
      shell: source /etc/kolla/admin-openrc.sh;openstack server show test-sriov | grep addresses | awk {' print $4'}|awk '{split($0,a,"=");print a[2]}'
      args:
       executable: /bin/bash
      register: ip
    - debug: var=ip

    - name: Test ping from localhost
      wait_for: host={{ ip.stdout }} port=22 timeout=900
    - debug: msg=ok

    - name: Check ping from SRIOV instance
      command: ssh -o StrictHostKeyChecking=no ubuntu@{{ ip.stdout }} "ping {{ data_prefix }}.{{ controller_ip }} -c 5"
      register: result
    - debug:
        var: result


