openstack: 
  deployment_type: Kolla
  git_branch: stable/queens
  kolla_tag: ""
  kolla_ansible_tag: ""
  hosts: 
    -
      host:
        hostname: CONTROLLER22
        interfaces:
          -
            ip: ""
            mac: "c4:34:6b:b7:fc:30"
            name: eno1
            type: management
          -
            ip: ""
            mac: "c4:34:6b:b7:fc:31"
            name: eno2
            type: tenant
          -
            gateway: ""
            ip: ""
            mac: "c4:34:6b:b7:fc:32"
            name: eno3
            type: data
        isolcpus: ""
        reserved_host_memory_mb: ""
        node_type:
          - network
          - controller
          - storage
        second_storage:
          - "/dev/sdb"
          - "/dev/sdc"
        sriov_interface:
        password:
        service_host: ""
        user: root

    -
      host:
        hostname: COMPUTE23
        interfaces:
          -
            ip: ""
            mac: "38:63:bb:44:84:70"
            name: eno1
            type: management
          -
            ip: ""
            mac: "38:63:bb:44:84:71"
            name: eno2
            type: tenant
          -
            gateway: ""
            ip: ""
            mac: "38:63:bb:44:84:72"
            name: eno3
            type: data
        isolcpus: "0-15"
        reserved_host_memory_mb: "16384"
        node_type:
          - compute
        second_storage:
        sriov_interface:
          - enp4s0f0
        password: 
        service_host: ""
        user: root
    -
      host:
        hostname: COMPUTE24
        interfaces:
          -
            ip: ""
            mac: "38:63:bb:44:f4:cc"
            name: eno1
            type: management
          -
            ip: ""
            mac: "38:63:bb:44:f4:cd"
            name: eno2
            type: tenant
          -
            gateway: ""
            ip: ""
            mac: "38:63:bb:44:f4:ce"
            name: eno3
            type: data
        isolcpus: "0-15"
        reserved_host_memory_mb: "16384"
        node_type:
          - compute
        second_storage:
        sriov_interface:
          - enp4s0f0
        password: 
        service_host: ""
        user: root
    -
      host:
        hostname: COMPUTE25
        interfaces:
          -
            ip: ""
            mac: "c4:34:6b:b8:87:e4"
            name: eno1
            type: management
          -
            ip: ""
            mac: "c4:34:6b:b8:87:e5"
            name: eno2
            type: tenant
          -
            gateway: ""
            ip: ""
            mac: "c4:34:6b:b8:87:e6"
            name: eno3
            type: data
        isolcpus: "0-15"
        reserved_host_memory_mb: "16384"
        node_type:
          - compute
          - storage
        second_storage:
          - "/dev/sdb/"
        sriov_interface:
          - enp4s0f0
        password: 
        service_host: ""
        user: root
    -
      host:
        hostname: COMPUTE26
        interfaces:
          -
            ip: ""
            mac: "ec:b1:d7:8a:39:10"
            name: eno1
            type: management
          -
            ip: ""
            mac: "ec:b1:d7:8a:39:11"
            name: eno2
            type: tenant
          -
            gateway: ""
            ip: ""
            mac: "ec:b1:d7:8a:39:12"
            name: eno3
            type: data
        isolcpus: "0-15"
        reserved_host_memory_mb: "16384"
        node_type:
          - compute
          - storage
        second_storage:
          - "/dev/sdb/"
        sriov_interface:
          - enp4s0f0
        password: 
        service_host: ""
        user: root
  networks:
    external:
      gateway: ""
      ip_pool:
        start: ""      
        end: ""
      subnet: 
    tenant:
      subnet:
      subnet_size:
    mtu_size:
      default: 8000
      vxlan: 3000
  proxies:
    ftp_proxy: ""
    http_proxy: ""
    https_proxy: ""
    no_proxy: ""
  service_password: 
  services:
    - cinder
    - ceph
    - magnum
    - tempest
    - ceilometer
    - tacker
    - sriov
    - dpdk
  kolla:
     base_distro: "ubuntu"
     install_type: "source"
     keepalived_virtual_router_id: "13"
     internal_vip_address: ""
     internal_interface: "eno1"
     kolla_registry: ""
     kolla_registry_port: "4000"
     external_vip_address: ""
     external_interface: "eno3"
     pull_from_hub: "no"
     base_size: "573741824"
     count: "20"
