---
openstack:
  deployment_type: Kolla
  git_branch: stable/pike
  hosts:
    -
      host:
        hostname: controller
        interfaces:
          -
            gateway: "10.197.131.1"
            ip: "10.197.131.12"
            name: eno1
            type: management
          -
            gateway: "10.197.132.1"
            ip: "10.197.132.12"
            name: eno2
            type: tenant
          -
            gateway: "10.197.133.1"
            ip: "10.197.133.12"
            name: eno3
            type: data
            dns: 8.8.8.8
        isolcpus: ""
        reserved_host_memory_mb: ""
        node_type:
          - controller
          - network
        password: cable123
        service_host: ""
        user: root
    -
      host:
        hostname: compute1
        interfaces:
          -
            gateway: "10.197.131.1"
            ip: "10.197.131.13"
            name: eno1
            type: management
          -
            gateway: "10.197.132.1"
            ip: "10.197.132.13"
            name: eno2
            type: tenant
          -
            gateway: "10.197.133.1"
            ip: "10.197.133.13"
            name: eno3
            type: data
            dns: 8.8.8.8
        isolcpus: ""
        reserved_host_memory_mb: "16384"
        node_type:
          - compute
          - storage
        second_storage: "/dev/sdb"
        password: cable123
        service_host: "10.197.131.12"
        user: root
    -
      host:
        hostname: compute2
        interfaces:
          -
            gateway: "10.197.131.1"
            ip: "10.197.131.14"
            name: eno1
            type: management
          -
            gateway: "10.197.132.1"
            ip: "10.197.132.14"
            name: eno2
            type: tenant
          -
            gateway: "10.197.133.1"
            ip: "10.197.133.14"
            name: eno3
            type: data
            dns: 8.8.8.8
        isolcpus: ""
        reserved_host_memory_mb: "16384"
        node_type:
          - compute
          - storage
        second_storage: "/dev/sdb"
        password: cable123
        service_host: "10.197.131.12"
        user: root
    -
      host:
        hostname: compute3
        interfaces:
          -
            gateway: "10.197.131.1"
            ip: "10.197.131.15"
            name: eno1
            type: management
          -
            gateway: "10.197.132.1"
            ip: "10.197.132.15"
            name: eno2
            type: tenant
          -
            gateway: "10.197.133.1"
            ip: "10.197.133.15"
            name: eno3
            type: data
            dns: 8.8.8.8
        isolcpus: ""
        reserved_host_memory_mb: "16384"
        node_type:
          - compute
          - storage
        second_storage: "/dev/sdb"
        password: cable123
        service_host: "10.197.131.12"
        user: root
  networks:
    external:
      gateway: "10.197.133.1"
      ip_pool:
        start: "10.197.133.100"
        end: "10.197.133.254"
      subnet: 10.197.133.0/24
    tenant:
      subnet:
      subnet_size:
    mtu_size:
       default: 8000
       vxlan: 1500
  proxies:
    ftp_proxy: ""
    http_proxy: ""
    https_proxy: ""
    no_proxy: ""
  service_password: cable123
  services:
    - magnum
    - tempest
    - ceilometer
    - ceph
    - cinder
    - tacker
  kolla:
     base_distro: "ubuntu"
     install_type: "source"
     keepalived_virtual_router_id: "30"
     internal_vip_address: "10.197.131.30"
     internal_interface: "eno1"
     kolla_registry: "10.197.131.12"
     kolla_registry_port: "4000"
     external_vip_address: "10.197.133.30"
     external_interface: "eno3"
     pull_from_hub: "yes"
     docker_namespace: "snapsopenstack"
     base_size: "573741824"
     count: "20"
