openstack: 
  deployement_type: Kolla
  git_branch: stable/pike
  hosts: 
    -
      host:
        hostname: CONTROLLER22
        interfaces:
          -
            ip: "10.197.101.22"
            mac: "c4:34:6b:b7:fc:30"
            name: eno1
            type: management
          -
            ip: "10.197.102.22"
            mac: "c4:34:6b:b7:fc:31"
            name: eno2
            type: tenant
          -
            gateway: "10.197.103.1"
            ip: "10.197.103.22"
            mac: "c4:34:6b:b7:fc:32"
            name: eno3
            type: data
        isolcpus: ""
        reserved_host_memory_mb: ""
        node_type:
          - network
          - controller
          - storage
        password: cable123
        service_host: ""
        user: root

    -
      host:
        hostname: COMPUTE23
        interfaces:
          -
            ip: "10.197.101.23"
            mac: "38:63:bb:44:84:70"
            name: eno1
            type: management
          -
            ip: "10.197.102.23"
            mac: "38:63:bb:44:84:71"
            name: eno2
            type: tenant
          -
            gateway: "10.197.103.1"
            ip: "10.197.103.23"
            mac: "38:63:bb:44:84:72"
            name: eno3
            type: data
        isolcpus: "0-15"
        reserved_host_memory_mb: "16384"
        node_type:
          - compute
        password: cable123
        service_host: "10.197.101.22"
        user: root
    -
      host:
        hostname: COMPUTE24
        interfaces:
          -
            ip: "10.197.101.24"
            mac: "38:63:bb:44:f4:cc"
            name: eno1
            type: management
          -
            ip: "10.197.102.24"
            mac: "38:63:bb:44:f4:cd"
            name: eno2
            type: tenant
          -
            gateway: "10.197.103.1"
            ip: "10.197.103.24"
            mac: "38:63:bb:44:f4:ce"
            name: eno3
            type: data
        isolcpus: "0-15"
        reserved_host_memory_mb: "16384"
        node_type:
          - compute
        password: cable123
        service_host: "10.197.101.22"
        user: root
    -
      host:
        hostname: COMPUTE25
        interfaces:
          -
            ip: "10.197.101.25"
            mac: "c4:34:6b:b8:87:e4"
            name: eno1
            type: management
          -
            ip: "10.197.102.25"
            mac: "c4:34:6b:b8:87:e5"
            name: eno2
            type: tenant
          -
            gateway: "10.197.103.1"
            ip: "10.197.103.25"
            mac: "c4:34:6b:b8:87:e6"
            name: eno3
            type: data
        isolcpus: "0-15"
        reserved_host_memory_mb: "16384"
        node_type:
          - compute
          - storage
        password: cable123
        service_host: "10.197.101.22"
        user: root
    -
      host:
        hostname: COMPUTE26
        interfaces:
          -
            ip: "10.197.101.26"
            mac: "ec:b1:d7:8a:39:10"
            name: eno1
            type: management
          -
            ip: "10.197.102.26"
            mac: "ec:b1:d7:8a:39:11"
            name: eno2
            type: tenant
          -
            gateway: "10.197.103.1"
            ip: "10.197.103.26"
            mac: "ec:b1:d7:8a:39:12"
            name: eno3
            type: data
        isolcpus: "0-15"
        reserved_host_memory_mb: "16384"
        node_type:
          - compute
          - storage
        password: cable123
        service_host: "10.197.101.22"
        user: root
  networks:
    external:
      gateway: "10.197.103.1"
      ip_pool:
        end: "10.197.103.236"
        start: "10.197.103.222"
      subnet: 10.197.103.0/24
    tenant:
      subnet:
      subnet_size:
    mtu_size:
      default: 8000
      vxlan: 3000
  proxies:
    ftp_proxy: ""
    http_proxy: ""
    https_proxy: ""
    no_proxy: ""
  service_password: cable123
  services:
    - cinder
    - magnum
    - tempest
    - ceilometer
    - tacker
  kolla:
     base_distro: "ubuntu"
     install_type: "source"
     keepalived_virtual_router_id: "13"
     internal_vip_address: "10.197.101.30"
     internal_interface: "eno1"
     kolla_registry: "10.197.101.22"
     kolla_registry_port: "4000"
     external_vip_address: "10.197.103.30"
     external_interface: "eno3"
     second_storage: ""
     base_size: "573741824"
     count: "20"

                              

